stages:
  - checkout
  - build
  - test
  - static_api_documentation
  - generate_client_jar
  - build_client_jar
  - build_artifacts
  - publish_artifacts
variables:
  environment: "dev"
  artifact_name: "default-artifact"
  build_tool: "maven"   # Default build tool
  notify_channel: "#devops-alerts"  # Default Slack notification channel
