stages:
  - name: checkout
    enabled: true
  - name: build
    enabled: true
  - name: test
    enabled: true
  - name: static_api_documentation
    enabled: true
  - name: generate_client_jar
    enabled: true
  - name: build_client_jar
    enabled: true
  - name: build_artifacts
    enabled: true
  - name: publish_artifacts
    enabled: true

variables:
  environment: "dev"
  artifact_name: "default-artifact"
  build_tool: "maven"   # Default build tool
  notify_channel: "#devops-alerts"  # Default Slack notification channel
